'use client';

import { useState } from 'react';
import { Sparkles, X, BrainCircuit, AlertCircle } from 'lucide-react';

interface AIAnalysisModalProps {
  stockSymbol: string;
  stockName: string;
  isOpen: boolean;
  onClose: () => void;
}

export function AIAnalysisModal({ stockSymbol, stockName, isOpen, onClose }: AIAnalysisModalProps) {
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Function to fetch analysis (mocked for now, can be connected to real AI action later)
  const fetchAnalysis = async () => {
    setIsLoading(true);
    setError(null);
    try {
        // Simulate API call
        await new Promise(resolve => setTimeout(resolve, 2000));
        
        // Mock Response
        setAnalysis(`Based on the fundamental data for ${stockName} (${stockSymbol}), here is a brief AI assessment:

1. **Valuation**: The P/E ratio suggests the stock is trading at a premium compared to its historical average.
2. **Growth**: Revenue growth has been consistent, but profit margins are slightly compressing due to increased operational costs.
3. **Volatility**: A Beta of 1.2 indicates higher volatility than the broader market, suitable for aggressive investors.
4. **Dividend**: The yield is modest, but the payout ratio is sustainable.

**Overall Sentiment**: Hold/Accumulate for long-term growth, but watch for short-term corrections.`);
    } catch (err) {
        setError('Failed to generate analysis. Please try again.');
    } finally {
        setIsLoading(false);
    }
  };

  // Trigger fetch when opened
  if (isOpen && !analysis && !isLoading && !error) {
      fetchAnalysis();
  }

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white dark:bg-gray-900 rounded-2xl w-full max-w-lg p-6 border border-gray-100 dark:border-gray-800 shadow-2xl relative flex flex-col max-h-[80vh]">
        
        {/* Header */}
        <div className="flex items-center justify-between mb-4">
             <div className="flex items-center gap-2 text-violet-600 dark:text-violet-400">
                <BrainCircuit size={24} />
                <h3 className="text-lg font-bold text-gray-900 dark:text-white">AI Fundamental Analysis</h3>
             </div>
             <button 
                onClick={onClose}
                className="p-2 text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-800 rounded-full transition-colors"
             >
                <X size={20} />
             </button>
        </div>

        {/* Content */}
        <div className="overflow-y-auto flex-1 pr-2">
            {isLoading ? (
                <div className="flex flex-col items-center justify-center py-12 space-y-4">
                    <Sparkles className="animate-spin text-violet-500" size={32} />
                    <p className="text-sm text-gray-500 font-medium animate-pulse">Analyzing market data...</p>
                </div>
            ) : error ? (
                <div className="flex flex-col items-center justify-center py-8 text-center space-y-2">
                    <AlertCircle className="text-red-500" size={32} />
                    <p className="text-sm text-gray-900 dark:text-gray-100">{error}</p>
                    <button onClick={fetchAnalysis} className="text-xs text-blue-500 hover:underline">Try Again</button>
                </div>
            ) : (
                <div className="prose dark:prose-invert prose-sm max-w-none">
                    <div className="bg-violet-50 dark:bg-violet-900/10 p-4 rounded-xl border border-violet-100 dark:border-violet-800 mb-4">
                        <p className="text-xs text-violet-700 dark:text-violet-300 font-medium leading-relaxed">
                            Disclaimer: This analysis is generated by AI and should not be considered as financial advice. Always do your own research.
                        </p>
                    </div>
                    <div className="whitespace-pre-wrap leading-relaxed text-gray-700 dark:text-gray-300">
                        {analysis}
                    </div>
                </div>
            )}
        </div>
      </div>
    </div>
  );
}
